#!/bin/bash

DIR="$(dirname "$0")"
source $DIR/bin/load-env

backup_directories=(${BACKUP_DIRECTORIES//,/ })       # Splitting by colon into an array

# Run restic backup
echo "Running backup on: ${backup_directories[@]}"
$DIR/restic backup "${backup_directories[@]}" "$@"

if [ $? -eq 0 ]; then
    echo "Backup completed successfully!"
    echo 
    
    $DIR/cleanup
elif [ $? -eq 3 ]; then
    echo "Backup failed to copy some source files. Exit code 3."
else
    echo "Backup failed, see logs."
fi
