#!/bin/bash
DIR="$(dirname "$0")"
output=$($DIR/restic ls latest --human-readable -l "$@" | tail -n +2 | grep -v ^d | awk '{print $4 " " $5 ",", $NF}' | column -t -s ',')

first_line=$($DIR/restic ls latest --human-readable -l "$@" | head -n 1)
echo "$first_line"
echo "$output"
