#!/bin/bash

DIR="$(dirname "$0")"
source $DIR/bin/load-env

if [ -n "$RESTIC_PASSWORD_FILE" ]; then
    $RESTIC_PASSWORD=$(cat "$RESTIC_PASSWORD_FILE")
elif [ -n "$RESTIC_PASSWORD_COMMAND" ]; then
    $RESTIC_PASSWORD=$(eval "$RESTIC_PASSWORD_COMMAND")
fi

echo "Restic is initializing remote: $RESTIC_REPOSITORY" 
echo -n "$RESTIC_PASSWORD" | $DIR/bin/restic -r $RESTIC_REPOSITORY init --from-password-file=-