#!/bin/bash

DIR="$(dirname "$0")"
source $DIR/bin/load-env

VERBOSE=false

for arg in "$@"; do
    if [ "$arg" == "-v" ] || [ "$arg" == "--verbose" ]; then
        VERBOSE=true
        break
    fi
done

if [ "$VERBOSE" == true ]; then
    echo "Restic is using remote: $RESTIC_REPOSITORY" 
fi

if [ -n "$RESTIC_PASSWORD_FILE" ]; then
    $RESTIC_PASSWORD=$(cat "$RESTIC_PASSWORD_FILE")
elif [ -n "$RESTIC_PASSWORD_COMMAND" ]; then
    $RESTIC_PASSWORD=$(eval "$RESTIC_PASSWORD_COMMAND")
fi

# Call restic with the provided arguments
env RESTIC_PASSWORD="$RESTIC_PASSWORD" $DIR/bin/restic -r $RESTIC_REPOSITORY "$@"
