#!/bin/bash

DIR="$(dirname "$0")"
source $DIR/bin/load-env

backup_directories=(${BACKUP_DIRECTORIES//,/ })       # Splitting by colon into an array

# Iterate over backup locations
for location in "${backup_directories[@]}"; do
    echo "Restoring from backup location: $location"
    
    # Perform the restore using restic
    $DIR/restic restore latest:$location --target "$location" "$@"
    
    echo "Restore complete for: $location"
    echo
done